export const skills = [
  { skill: "AI & Agentic Applications" },
  { skill: "Distributed Systems Architecture" },
  { skill: "System Design & Clean Architecture" },
  { skill: "Python & Machine Learning" },
  { skill: "TypeScript & JavaScript" },
  { skill: "React & Next.js" },
  { skill: "Java & Kotlin" },
  { skill: "Modern C++" },
  { skill: "AWS & Cloud Infrastructure" },
  { skill: "Docker & Containerization" },
  { skill: "Database Design & Optimization" },
  { skill: "Embedded Systems Development" },
  { skill: "Web Technologies (HTML/CSS)" },
];
